import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Desktop } from "../src/components/Desktop";
import { Mobile } from "../src/components/Mobile";
import { Tablet } from "../src/components/Tablet";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Desktop>PC</Desktop>
      <Tablet>TABLET</Tablet>
      <Mobile>MOBILE</Mobile>
    </div>
  );
};

export default Home;
